name: Test python application

on:
  push:
    branches: [ "dev", "stable" ]
  pull_request:
    branches: [ "dev", "stable" ]

permissions:
  contents: read

jobs:
  build:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOs
        py:
          - "3.12"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-bugbear flake8-docstrings flake8-import-order flake8-colors pep8-naming pytest pytest-cov
        pip install .[test]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Now run the full flake check
        flake8 . --count --statistics
    - name: Setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
    - name: Test with pytest
      run: |
        pytest --cov m4b_util --cov-report term-missing --cov-fail-under=100
