name: Test Python Application

on:
  push:
    branches: "**"
  pull_request:
    branches: [ "dev", "stable" ]

permissions:
  contents: read

jobs:
  build:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Windows
        py:
          - "3.12"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage[toml] .
    - name: Setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
    - name: Test with pytest
      run: |
        pytest --cov m4b_util --cov-report term-missing --cov-fail-under=100 -k "test_print_version"
