name: Test Python Application

on:
  workflow_run:
    workflows: ["Lint Python Application"]
    types:
      - completed


jobs:
  build:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
        py:
          - "3.12"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage[toml] .
    - name: Setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
    - name: Test with pytest
      run: |
        pytest --cov m4b_util --cov-report term-missing --cov-branch --cov-fail-under=100
